### ISSUE TITLE
fails with kicad 6.0.11

### ISSUE THREAD

**Issue by folkertvanheusden** [matterwaves/A100PanelGenerator#1]
I get the error: module 'pcbnew' has no attribute 'DRAWSEGMENT'

```
A100FrontPanel().generatePanel()
Board width: 71.22 mm, --> 16.0 hp panel with 5.030000000000001 mm clearance/side 
Board height: 86.46 mm --> 12.770000000000003 mm clearance on top and bottom
Board Center: (213360000, 83820000) nm
getting dimensions
Board width: 71.22 mm, --> 16.0 hp panel with 5.030000000000001 mm clearance/side 
Board height: 86.46 mm --> 12.770000000000003 mm clearance on top and bottom
Board Center: (213360000, 83820000) nm
drawing edges
Traceback (most recent call last):
  File "/usr/lib/python3.11/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/folkert/Projects/kicad/A100PanelGenerator/A100FrontPanel.py", line 241, in generatePanel
    self.drawEdges()
  File "/home/folkert/Projects/kicad/A100PanelGenerator/A100FrontPanel.py", line 144, in drawEdges
    ds=pcbnew.DRAWSEGMENT(self.fp)
       ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pcbnew' has no attribute 'DRAWSEGMENT'
```

**Comment by stormyweathers** [comment]
This is a known issue with kicad 6.  They changed the python API, and I haven't been able to find documentation for the changes.  I will happily fix this myself if you can point me to the proper docs.
